apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-config
data:
  application.properties: |
    spring.datasource.url=jdbc:postgresql://dpg-cndlhumn7f5s73blu650-a.oregon-postgres.render.com/dbdistribuida
    spring.datasource.username=dbdistribuida_user
    spring.datasource.password=lyNbzGn80aIkIbA7SvR5t8DhAbxUo7d6
    app.authors.url=http://localhost:8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-books
  template:
    metadata:
      labels:
        app: app-books
    spec:
      containers:
        - name: app-books
          image: nacarrera/app-books
          ports:
            - containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: app-books-service
spec:
  type: ClusterIP
  selector:
    app: app-books
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090