version: '1'
services:
  discovery:
    image: consul:1.17
    ports:
      - 8500:8500
  service-app-author:
    image: violentpanda1007/app-authors
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery
    depends_on:
      - discovery

---
gateway:
  image: library/gateway
  ports:
    8080:8080
  environment:
    - JAVA_TOOL_OPTIONS=
      -DCONSUL_HOST=discovery
  depends_on:
    - discovery

